- hosts: localhost
  gather_facts: False
  vars_files:
    - vault.yml
    - vars.yml
  tasks:
    - name: Print the value
      debug: 
        msg: "{{ item }}"
      with_items: sudo_users
# - hosts: localhost
#   connection: local
#   gather_facts: False

#   tasks:
#     - name: Create Backend Droplet.
#       digital_ocean:
#         api_token: "{{ lookup('env', 'DO_API_TOKEN') }}"
#         state: present
#         command: droplet
#         name: faragalla_backend
#         private_networking: yes
#         size_id: s-1vcpu-1gb
#         # size_id: s-2vcpu-4gb
#         image_id: ubuntu-16-04-x64
#         region_id: ams3
#         # Customize this for your account.
#         ssh_key_ids: 19808077
#         # ssh_key_ids: 19826613
#         # Required for idempotence/only one droplet creation.
#         unique_name: yes
#         backups_enabled: no
#         wait_timeout: 600
#         user_data: "{{ lookup('file', 'user-data.yml') }}"
#       register: do_backend

#     - name: Add new host to our inventory.
#       add_host:
#         name: "fargalla_backend"
#         ansible_host: "{{ do_backend.droplet.ip_address }}"
#         groups:
#           - "{{ do_backend.droplet.private_ip_address }}"
#       when: do_backend.droplet is defined
#       changed_when: False
    
#     - name: Debug added host
#       debug:
#         # var: hostvars
#         msg: "{{ hostvars['fargalla_backend']['group_names'][0] }}"
  
# # - hosts: fargalla_backend
# #   remote_user: root
# #   vars_files:
# #     - vault.yml
# #     - vars.yml
# #   tasks:
# #     - name: Is it working?
# #       debug:
# #         var: hostvars